[package]
name = "xynotes"
version = "4.0.0"
description = "一个轻量级的本地笔记本"
authors = ["xygengcn"]
license = ""
repository = "https://github.com/xygengcn/XYNotes"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [ "clipboard-all", "window-set-focus", "window-unmaximize", "window-unminimize", "window-start-dragging", "window-hide", "system-tray", "window-close", "window-create", "fs-write-file", "dialog-save", "window-minimize", "window-maximize", "window-show", "window-set-minimizable", "window-set-closable", "window-center", "window-set-min-size", "window-set-fullscreen", "app-show", "app-hide", "macos-private-api", "shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
